// import { EnumUiOption, UiLocalization } from '../types/identy';

export const LOCALIZATIONSOCR: any[] = [
  {
    name: 'English',
    selected: false,
    localization: {
      en: {
        FEEDBACK_CAPTURED: 'Captured Successfully',
        FEEDBACK_SEARCHING_BARCODE: 'Position Barcode in the frame',
        FEEDBACK_SEARCHING: 'Use {0} Side',
        FEEDBACK_SEARCHING_2: 'Place your card',
        FEEDBACK_SEARCHING_A4: 'Please place your document',
        FEEDBACK_SEARCHING_A4_2: 'Searching for form, Move away',
        FEEDBACK_SEARCHING_QRCODE: 'Place your Qrcode',
        FEEDBACK_INSIDE_GUIDE: 'Please be inside the guide',
        FEEDBACK_INSIDE_GUIDE_A4: 'Move further away',
        FEEDBACK_PLEASE_HOLD: 'Please hold.',
        FEEDBACK_STABLE: 'Please be stable',
        FEEDBACK_A4_LEFT_ALIGNED: 'Please center document',
        FEEDBACK_A4_RIGHT_ALIGNED: 'Please center document',
        FEEDBACK_CLOSE: 'Please move closer',
        FEEDBACK_FAR: 'Please move further away',
        FEEDBACK_BLURRY: 'Wait for camera to focus',
        FEEDBACK_TILTED: 'Card too rotated',
        FEEDBACK_NOT_STABLE: 'Please be stable',
        FEEDBACK_OK: 'Please Hold',
        FEEDBACK_ATTEMPT_TIMEOUT_EXCEEDED: 'Timeout exceeded.',
        FEEDBACK_NO_DATA: 'Please be stable and avoid shadows or reflections',
        FEEDBACK_BARCODE_NO_DATA: 'Cannot extract Barcodes from image',
        FEEDBACK_NOT_PARALLEL: 'Please be parallel to doc',
        FEEDBACK_CAMERA_ACQUIRING_FAILED:
          'Cannot acquire camera, Allow permission Or Retry Capture',
        FEEDBACK_PROCESSING: 'Processing...',
        FEEDBACK_UPLOADING: 'Uploading debug images...',
        FEEDBACK_UPLOAD_FAILURE: 'Internal error retry',
        FEEDBACK_INITIALIZATION: 'Initializing...',
        FEEDBACK_CROPPING: 'Cropping...',
        FEEDBACK_RECOGNITION: 'Running OCR...',
        FEEDBACK_CHANGE_LIGHT: 'Avoid shadows',
        FEEDBACK_BUTTON_CLOSE: 'Close',
        FEEDBACK_BUTTON_RETRY: 'Retry',
        FEEDBACK_TRAINING_BUTTON_NEXT: 'Next',
        FEEDBACK_TRAINING_LABEL: "Don't Show me again",
        FEEDBACK_LICENCE_INVALID: 'License Invalid!!',
        FEEDBACK_ORIENTATION_NOT_SUPPORTED: 'Only Portrait mode is supported',
        FEEDBACK_CHECK_QUALITY_MESSAGE:
          'Please check that image is clear, with no blur or glare.',
        FEEDBACK_CAPTURE_BACK_SIDE: 'Select the backside of card',
        ERROR_FILE_FRONT_WRONG_SIDE: 'Invalid front side selected',
        ERROR_FILE_BACK_WRONG_SIDE: 'Invalid back side selected',
        ERROR_FILE_WRONG_POA_TYPE: 'Wrong document type selected',
        ERROR_BROWSER_NOT_SUPPORTED:
          'Browser not supported, Please update to Latest Chrome, Firefox (Android) or Safari on IOS.',
        ERROR_WEBRTC_NOT_SUPPORTED: 'Webrtc not supported',
        ERROR_MODEL_FAIL: 'Model detection failed',
        ERROR_SERVER_INTERNAL: 'Internal Server Error',
        ERROR_DEVICE_NOT_SUPPORTED: 'WEBGL Not supported.',
        ERROR_SERVER_CONNECTION_FAILURE: 'Server connection failure',
        FEEDBACK_BACK_WRONG_SIDE: 'Please put the back side',
        FEEDBACK_FRONT_WRONG_SIDE: 'Please put the front side',
        FEEDBACK_WRONG_POA_TYPE: 'Present a valid POA document',
        FACE: {
          FRONT: 'Front',
          BACK: 'Back',
          QRCODE: 'QRCODE',
        },
        BUTTON: {
          CROP: 'Crop',
          NEXT: 'Continue',
          CANCEL: 'Cancel',
          RETAKE: 'Retake',
        },
      },
    },
  },
  {
    name: 'Spanish',
    selected: true,
    localization: {
      es: {
        FEEDBACK_CAPTURED: 'Captura exitosa',
        FEEDBACK_SEARCHING_BARCODE: 'Posicione el código de barras en el marco',
        FEEDBACK_SEARCHING: 'Utilice el lado {0}',
        FEEDBACK_SEARCHING_2: 'Coloque su tarjeta',
        FEEDBACK_SEARCHING_A4: 'Por favor coloque su documento',
        FEEDBACK_SEARCHING_A4_2: 'Buscando formulario, Aléjese',
        FEEDBACK_SEARCHING_QRCODE: 'Coloque su código QR',
        FEEDBACK_INSIDE_GUIDE: 'Por favor, manténgase dentro de la guía',
        FEEDBACK_INSIDE_GUIDE_A4: 'Aléjese más',
        FEEDBACK_PLEASE_HOLD: 'Por favor, espere.',
        FEEDBACK_STABLE: 'Por favor, manténgase estable',
        FEEDBACK_A4_LEFT_ALIGNED: 'Por favor, centre el documento',
        FEEDBACK_A4_RIGHT_ALIGNED: 'Por favor, centre el documento',
        FEEDBACK_CLOSE: 'Por favor, acérquese',
        FEEDBACK_FAR: 'Por favor, aléjese',
        FEEDBACK_BLURRY: 'Espere a que la cámara enfoque',
        FEEDBACK_TILTED: 'Tarjeta demasiado girada',
        FEEDBACK_NOT_STABLE: 'Por favor, manténgase estable',
        FEEDBACK_OK: 'Por favor, espere',
        FEEDBACK_ATTEMPT_TIMEOUT_EXCEEDED: 'Tiempo de espera excedido.',
        FEEDBACK_NO_DATA:
          'Por favor, manténgase estable y evite sombras o reflejos',
        FEEDBACK_BARCODE_NO_DATA:
          'No se pueden extraer los códigos de barras de la imagen',
        FEEDBACK_NOT_PARALLEL: 'Por favor, paralelo al documento',
        FEEDBACK_CAMERA_ACQUIRING_FAILED:
          'No se puede adquirir la cámara, Permita el permiso o reintente la captura',
        FEEDBACK_PROCESSING: 'Procesando...',
        FEEDBACK_UPLOADING: 'Subiendo imágenes de depuración...',
        FEEDBACK_UPLOAD_FAILURE: 'Error interno, reintente',
        FEEDBACK_INITIALIZATION: 'Inicializando...',
        FEEDBACK_CROPPING: 'Recortando...',
        FEEDBACK_RECOGNITION: 'Ejecutando OCR...',
        FEEDBACK_CHANGE_LIGHT: 'Evite sombras',
        FEEDBACK_BUTTON_CLOSE: 'Cerrar',
        FEEDBACK_BUTTON_RETRY: 'Reintentar',
        FEEDBACK_TRAINING_BUTTON_NEXT: 'Siguiente',
        FEEDBACK_TRAINING_LABEL: 'No mostrar de nuevo',
        FEEDBACK_LICENCE_INVALID: '¡Licencia inválida!',
        FEEDBACK_ORIENTATION_NOT_SUPPORTED: 'Solo se admite el modo retrato',
        FEEDBACK_CHECK_QUALITY_MESSAGE:
          'Por favor, verifique que la imagen esté clara, sin desenfoques o reflejos.',
        FEEDBACK_CAPTURE_BACK_SIDE: 'Seleccione el reverso de la tarjeta',
        ERROR_FILE_FRONT_WRONG_SIDE: 'Lado frontal seleccionado inválido',
        ERROR_FILE_BACK_WRONG_SIDE: 'Lado posterior seleccionado inválido',
        ERROR_FILE_WRONG_POA_TYPE: 'Tipo de documento seleccionado incorrecto',
        ERROR_BROWSER_NOT_SUPPORTED:
          'Navegador no compatible, Por favor actualice a la última versión de Chrome, Firefox (Android) o Safari en IOS.',
        ERROR_WEBRTC_NOT_SUPPORTED: 'Webrtc no es compatible',
        ERROR_MODEL_FAIL: 'La detección del modelo falló',
        ERROR_SERVER_INTERNAL: 'Error interno del servidor',
        ERROR_DEVICE_NOT_SUPPORTED: 'WEBGL No es compatible.',
        ERROR_SERVER_CONNECTION_FAILURE: 'Fallo en la conexión con el servidor',
        FEEDBACK_BACK_WRONG_SIDE: 'Por favor, coloque el lado posterior',
        FEEDBACK_FRONT_WRONG_SIDE: 'Por favor, coloque el lado frontal',
        FEEDBACK_WRONG_POA_TYPE: 'Presente un documento de POA válido',
        FACE: {
          FRONT: 'Frente',
          BACK: 'Reverso',
          QRCODE: 'CÓDIGO QR',
        },
        BUTTON: {
          CROP: 'Recortar',
          NEXT: 'Continuar',
          CANCEL: 'Cancelar',
          RETAKE: 'Rehacer',
        },
      },
    },
  },
];

export const LOCALIZATIONSFACE: any[] = [
  {
    name: 'English',
    selected: false,
    option: {
      en: {
        FEEDBACK_CAPTURED: 'Captured Successfully',
        FEEDBACK_SEARCHING: 'Searching',
        FEEDBACK_INSIDE_GUIDE: 'Please be inside the guide',
        FEEDBACK_PLEASE_HOLD: 'Please hold',
        FEEDBACK_EYE_LEVEL: 'Look Straight',
        FEEDBACK_UP_FACING: 'Look Down to be parallel to camera',
        FEEDBACK_DOWN_FACING: 'Look up to be parallel to camera',
        FEEDBACK_FACE_OUTSIDE: 'Please be inside guide',
        FEEDBACK_CLOSE: 'Move Away',
        FEEDBACK_FAR: 'Move Close',
        FEEDBACK_LEFT_FACING: 'Looking Left, Please Look straight',
        FEEDBACK_RIGHT_FACING: 'Looking Right, Please Look straight',
        FEEDBACK_ROTATED: 'Look Straight',
        FEEDBACK_NOT_STABLE: 'Please be stable',
        FEEDBACK_OK: 'Please Hold',
        FEEDBACK_NOT_CENTERED: 'Center Face in oval',
        FEEDBACK_PROCESSING: 'Processing...',
        FEEDBACK_INITIALIZATION: 'Initializing...',
        FEEDBACK_CHANGE_LIGHT: 'Avoid shadows',
        FEEDBACK_CHANGE_LIGHT_TOO_BRIGHT:
          'Too Bright, Move to better lighting.',
        FEEDBACK_CHANGE_LIGHT_TOO_DARK: 'Too Dark, Move to better lighting.',
        FEEDBACK_TRAINING_BUTTON_NEXT: 'Next',
        FEEDBACK_TRAINING_LABEL: 'Dont Show again',
        FEEDBACK_ONLY_PORTRAIT:
          'Capture Works only in <strong>portrait</strong> mode',
        FEEDBACK_RETAKE_HEADER: 'We need to capture again.',
        FEEDBACK_RETAKE_CONTENT: 'Please look for better lighting',
        FEEDBACK_RETAKE_YOUR_IMAGE: 'Your Image',
        FEEDBACK_RETAKE_OPTIMAL_IMAGE: 'Optimal Image',
        FEEDBACK_RETAKE_BUTTON: 'Capture again',
        FEEDBACK_RETAKE_BUTTON_CLOSE: 'Close',
      },
    },
  },
  {
    name: 'Spanish',
    selected: true,
    option: {
      en: {
        FEEDBACK_CAPTURED: 'Captura exitosa',
        FEEDBACK_SEARCHING: 'Buscando',
        FEEDBACK_INSIDE_GUIDE: 'Coloque su cara dentro del óvalo',
        FEEDBACK_PLEASE_HOLD: 'No se mueva',
        FEEDBACK_EYE_LEVEL: 'Mire de frente',
        FEEDBACK_UP_FACING:
          'Inclina la cabeza hacia abajo, barbilla perpendicular al dispositivo',
        FEEDBACK_DOWN_FACING:
          'Inclina la cabeza hacia arriba, barbilla perpendicular al dispositivo',
        FEEDBACK_FACE_OUTSIDE: 'Coloque su cara dentro del óvalo',
        FEEDBACK_CLOSE: 'Aléjese del dispositivo',
        FEEDBACK_FAR: 'Acérquese al dispositivo',
        FEEDBACK_LEFT_FACING:
          'Cabeza inclinada hacia la izquierda, mire de frente',
        FEEDBACK_RIGHT_FACING:
          'Cabeza inclinada hacia la derecha, mire de frente',
        FEEDBACK_ROTATED: 'Mire de frente',
        FEEDBACK_NOT_STABLE: 'No se mueva',
        FEEDBACK_OK: 'No se mueva',
        FEEDBACK_NOT_CENTERED: 'Coloque su cara dentro del óvalo',
        FEEDBACK_PROCESSING: 'Procesando...',
        FEEDBACK_INITIALIZATION: 'Inicializando...',
        FEEDBACK_CHANGE_LIGHT: 'Evite reflejos y sombras',
        FEEDBACK_CHANGE_LIGHT_TOO_BRIGHT:
          'Entorno muy iluminado, muévase a un entorno con mejor iluminación',
        FEEDBACK_CHANGE_LIGHT_TOO_DARK:
          'Entorno muy oscuro, muévase a un entorno con mejor iluminación',
        FEEDBACK_TRAINING_BUTTON_NEXT: 'Siguiente',
        FEEDBACK_TRAINING_LABEL: 'No mostrar de nuevo',
        FEEDBACK_ONLY_PORTRAIT: 'Posición <strong>vertical</strong> requerida',
        FEEDBACK_RETAKE_HEADER: 'Necesitamos recapturar',
        FEEDBACK_RETAKE_CONTENT: 'Muévase a un entorno con mejor iluminación',
        FEEDBACK_RETAKE_YOUR_IMAGE: 'Su captura',
        FEEDBACK_RETAKE_OPTIMAL_IMAGE: 'Captura óptima',
        FEEDBACK_RETAKE_BUTTON: 'Recaptura',
        FEEDBACK_RETAKE_BUTTON_CLOSE: 'Cerrar',
      },
    },
  },
];
